# Generated by Django 5.2.8 on 2025-11-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0003_alter_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer'),
        ),
    ]
