# Generated by Django 5.2.8 on 2025-11-15 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0004_alter_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(db_column='customer', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer'),
            preserve_default=False,
        ),
    ]
